### ISSUE TITLE
RSS feed links are 404ing

### ISSUE THREAD

**Issue by sbdchd** [adrian154/blog#15]
RSS feed has a URL like:

https://blog.bithole.dev/mc-report-system.html

instead of

https://blog.bithole.dev/blogposts/mc-report-system/

https://github.com/adrian154/blog/blob/3d893d8458a2f284c0926ecb041625ee5786704c/components/rss-feed.js#L12 looks related

**Comment by adrian154** [comment]
Fixed in a0f8b49d2b00014126587767766d00be6d7095c2
